language: scala
dist: trusty

scala:
  - 2.10.7

jdk:
  - openjdk8
  - openjdk10
  - openjdk11
  - oraclejdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt test scripted scalafmtCheckAll
